#!/bin/bash
bspc rule -r "*"
export EDITOR=vim
export SYS="$HOME"/scripts/system
export DEFAULT_NETWORK_INTERFACE=$(ip route | grep '^default' | awk '{print $5}' | head -n1)
export _JAVA_AWT_WM_NONREPARENTING=1

# monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# config
bspc config automatic_scheme    alternate
bspc config initial_polarity    second_child
bspc config border_width        1
bspc config window_gap          0
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config pointer_action1     move
bspc config pointer_action2     resize_side
bspc config pointer_action3     resize_corner
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus   false

## rules
# fixed-desktops
bspc rule -a terminal_fixed desktop=1 focus=on border=off follow=on
bspc rule -a install4j-burp-StartBurp desktop=2 focus=on state=floating center=true follow=on
bspc rule -a Vmware desktop=3 focus=on state=tiled follow=on
bspc rule -a VSCodium desktop=4 follow=on state=fullscreen border=off follow=on
# desktop 5 is for spotify from external rules script
bspc rule -a mpv desktop=6 focus=on state=fullscreen follow=on
bspc rule -a discord desktop=9 focus=on state=tiled border=off follow=on
bspc rule -a firefox:Navigator desktop=10 focus=on state=tiled follow=on

# firefox bookmarks window
bspc rule -a firefox:Places focus=on state=floating follow=on center=true rectangle=1440x900+0+0

# misc
bspc rule -a terminal_floating:Alacritty state=floating follow=on center=true rectangle=1440x900+0+0
bspc rule -a Gvim:gvim state=floating follow=on
bspc rule -a Pcmanfm:pcmanfm state=floating follow=on center=true
bspc rule -a vlc:vlc state=floating follow=on center=true
bspc rule -a 'Gimp-2.10' state=floating follow=on center=true rectangle=1440x900+0+0
bspc rule -a Sxiv state=floating follow=on center=true
bspc rule -a '*:pavucontrol:*' state=floating follow=on center=true
bspc rule -a Zathura state=tiled follow=on
bspc config external_rules_command "$SYS/external_rules.sh"

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc &

# set us keyboard-mapping
setxkbmap us &

# clipboard manager
clipster -d &

# wallpaper
"$HOME"/.fehbg &

# start some stuff late
"$SYS"/start_late.sh &

# clear zombie id's
true > "$HOME"/.cache/bspwm_node_visibility.log

# change screen res if in vm
if (sudo dmidecode | grep -A3 '^System Information' | grep -qi 'virtual'); then xrandr -s 1440x810; fi 2>/dev/null

pkill dunst && notify-send "BSPWM" "Boot successful"
