user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.engagement.ctrlTab.has-used", true);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.urlbar.shortcuts.bookmarks", false);
user_pref("browser.urlbar.shortcuts.tabs", false);
user_pref("browser.urlbar.showSearchSuggestionsFirst", false);
user_pref("browser.urlbar.suggest.engines", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.suggest.quicksuggest", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("font.name.monospace.x-western", "Comic Code");
user_pref("font.name.sans-serif.x-western", "Times New Roman");
user_pref("font.name.serif.x-western", "Arial");
user_pref("font.size.monospace.x-western", 16);
user_pref("reader.content_width", 5);
user_pref("reader.font_size", 10);
user_pref("reader.font_type", "serif");
user_pref("reader.line_height", 5);
user_pref("services.sync.prefs.sync.browser.urlbar.suggest.topsites", false);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("ui.textSelectBackground", "#ffffff");
user_pref("ui.textSelectForeground", "#000000");
user_pref("ui.textSelectBackgroundAttention", "#fdff32");
user_pref("ui.textSelectBackgroundDisabled", "#b0b0b0");
user_pref("ui.textHighlightBackground", "#fdff32");
user_pref("ui.textHighlightForeground", "#ffffff");
user_pref("view_source.wrap_long_lines", true);
