#git
alias gs='git status -sb'
alias ga='git add'
alias gl='git l'
alias glv='git lv'
alias gc='git commit -S'
alias gd='git diff'

#misc
alias burp='$HOME/opt/burp/start_burp.sh'
alias nmap='sudo nmap'
alias up='sudo python -m http.server'
alias gist='gist -pcsR --skip-empty'
alias sxiv='sxiv -r'
alias camera='mpv --demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg av://v4l2:/dev/video0'
alias dnd='dunstctl set-paused true'
alias dnd!='dunstctl set-paused false'

#general
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias szrc='source $HOME/.zshrc'
alias ali='vi $HOME/.zsh/aliases.zsh && szrc'
alias ip='ip -c -br a'
alias zc='vi $HOME/.zshrc && szrc'
alias ac='vi $HOME/.config/alacritty/alacritty.yml'
alias bsp='vi $HOME/.config/bspwm/bspwmrc'
alias x='chmod a+x'
alias c='bat'
alias cp='cp -v'
alias du='du -sh'
alias fd='fd -HI'
alias gdb='gdb -q'
alias ls='ls --group-directories-first --color=always'
alias l='ls'
alias la='ls -A'
alias ll='ls -lh'
alias lla='ls -lhA'
alias less='less -N'
alias mv='mv -i'
alias open='xdg-open'
alias p2='python2'
alias p='python'
alias pacman='s pacman'
alias r='ranger'
alias s='sudo'
alias su='s su'
alias sx='vi $HOME/.config/sxhkd/sxhkdrc'
alias todo='v $HOME/.todo && szrc'
alias v='vim'
alias sv='sudo vim'
alias vc='vi $HOME/.vimrc'
alias vi='v'
alias j='z' # zsh-z
alias copy='xclip -selection clipboard'
alias copy-img='xclip -selection clipboard -t image/png'
alias colorpicker='colorpicker --short --one-shot --preview | head -c -1 | xsel -b -i'
alias get_class='xprop | grep "WM_CLASS"'
alias info='echo -n "\n" ; neofetch | sed "16d"'

#no idea why I made them
alias clrdockerps='docker rm $(docker ps -a -f status=exited -f status=created -q) 2>/dev/null'
alias sl="echo -e \"\nIt's ls you DUMB-ASS\n\""
