#! /bin/bash
bspc rule -r "*"
export EDITOR=vim
export SYS="$HOME"/scripts/system
export _JAVA_AWT_WM_NONREPARENTING=1

# monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# config
bspc config automatic_scheme    alternate
bspc config initial_polarity    second_child
bspc config border_width        1
bspc config window_gap          0
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config pointer_action1  	move
bspc config pointer_action2     resize_side
bspc config pointer_action3     resize_corner
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus 	false

# rules

# fixed-desktops
bspc rule -a terminal_fixed desktop=1 focus=on border=off follow=on
bspc rule -a install4j-burp-StartBurp desktop=2 focus=on state=floating center=true follow=on
bspc rule -a Vmware desktop=3 focus=on state=tiled follow=on
bspc rule -a VSCodium desktop=4 follow=on state=fullscreen border=off follow=on
bspc rule -a mpv desktop=5 focus=on state=fullscreen follow=on
bspc rule -a superProductivity desktop=6 state=floating follow=on center=true
bspc rule -a discord desktop=9 focus=on state=tiled border=off follow=on
bspc rule -a Chromium desktop=10 focus=on state=tiled border=off follow=on

# misc
bspc rule -a terminal_floating state=floating follow=on center=true rectangle=1100x650+0+0
bspc rule -a MEGAsync state=floating follow=on center=true rectangle=400x570+0+0
bspc rule -a Pcmanfm state=floating follow=on center=true
bspc rule -a vlc state=floating follow=on center=true
bspc rule -a 'Gimp-2.10' state=floating follow=on center=true
bspc rule -a Sxiv state=floating follow=on center=true
bspc rule -a '*:pavucontrol:*' state=floating follow=on center=true
bspc rule -a Zathura state=tiled follow=on
bspc config external_rules_command "$SYS/external_rules.sh"

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# set us keyboard-mapping
setxkbmap us &

# clipboard manager
clipster -d &

# wallpaper
# if [ -d "$HOME"/Pictures/walls/rick_and_morty ]; then nitrogen --set-auto --random "$HOME"/Pictures/walls/rick_and_morty; fi
nitrogen --restore

# kill and start will delay
killall -q polybar
killall -q picom
"$SYS"/do.sh &

# clear scratchpad cache
true > "$HOME"/.cache/bspwm_node_visibility.log

# save my aging eyes
redshift -x && redshift -O 5800K

pkill dunst && notify-send "BSPWM" "Boot successful"
