#git
alias ga='git add -p'
alias gar='git add --all .'
alias gc='git commit -S -vv'
alias gca='git commit -S --amend'
alias gcr='git commit -S --amend --reuse-message=HEAD'
alias gd='git diff'
alias gl='git verboselog'
alias gll='git log'
alias gp='git push'
alias gs='{ git headlog 2>/dev/null || : } && git status -sb'
alias gb='git branch'
alias gch='git checkout'

#misc
alias nmap='sudo nmap'
alias up='sudo python -m http.server'
alias gist='gist -p --skip-empty'
alias sxiv='sxiv -r'
alias camera='mpv --demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg av://v4l2:/dev/video0'
alias dnd='dunstctl set-paused true'
alias dnd!='dunstctl set-paused false'
alias r32='tr -dc a-zA-Z0-9 < /dev/urandom | head -c 32 | copy'

#general
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias getcd="pwd | tr -d '\n' | copy"
alias rg="rg --hidden --glob '!.git'"
alias sc='source $HOME/.zshrc'
alias ali='$EDITOR $HOME/.zsh/zsh-config/10-aliases.zsh && sc'
alias ip='ip -c -br a'
alias zc='$EDITOR $HOME/.zshrc'
alias zd='$EDITOR $HOME/.zsh/zsh-config'
alias ac='$EDITOR $HOME/.config/alacritty/alacritty.yml'
alias bsp='$EDITOR $HOME/.config/bspwm/bspwmrc'
alias x='chmod a+x'
alias c='bat'
alias cp='cp -v'
alias du='du -sh'
alias fd='fd -HI'
alias gdb='gdb -q'
alias ls='ls --group-directories-first --color=always'
alias l='ls'
alias la='ls -A'
alias ll='ls -lh'
alias lla='ls -lhA'
alias less='less -Nr'
alias mv='mv -i'
alias open='xdg-open'
alias p2='python2'
alias p='python'
alias pacman='s pacman'
alias s='sudo'
alias su='s su'
alias sx='$EDITOR $HOME/.config/sxhkd/sxhkdrc'
alias v='vim'
alias vi='vim'
alias sv='sudo vim'
alias vc='$EDITOR $HOME/.vimrc'
alias copy='xclip -selection clipboard'
alias copy-img='xclip -selection clipboard -t image/png'
alias colorpicker='colorpicker --short --one-shot --preview | head -c -1 | copy'
alias get_class='xprop | grep "WM_CLASS"'
alias info='printf "\n" ; neofetch --config $HOME/.config/neofetch/config.conf | sed "16d"'

#no idea why I made them
alias clrdockerps='docker rm $(docker ps -a -f status=exited -f status=created -q) 2>/dev/null'
alias sl="echo -e \"\nIt's ls you DUMB-ASS\n\""
