# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# exports
export EDITOR='vim'
export TERM="xterm-256color"
export GOPATH="$HOME/go"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="/usr/local/go/bin:$GOPATH/bin:$PATH"

# source required zsh scripts
[[ -d "$HOME"/.zsh/zsh-config ]] &&
  for zsh_files in "$HOME"/.zsh/zsh-config/*.zsh
  do
    source "$zsh_files"
  done
