# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# exports
export EDITOR='vim'
export TERM="xterm-256color"

# update PATH
export PATH="$HOME/.local/bin:$PATH"

# go stuff
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"

# pyenv stuff
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# mason server binaries
export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"

# @@@ not sure why is it needed but just kept it here for now!
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# source my zsh scripts
[[ -d "$HOME"/.zsh/zsh-config ]] &&
  for zsh_files in "$HOME"/.zsh/zsh-config/*.zsh
  do
    source "$zsh_files"
  done
